name: PR CI com Databricks CLI e Assets Bundles

on:
  pull_request:

jobs:
  test-databricks:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v3

      # Passo 2: Instalar Python (se necessário)
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # ajuste conforme seu projeto

      # Passo 3: Instalar Databricks CLI
      - name: Install Databricks CLI
        run: pip install databricks-cli

      # Passo 4: Configurar Databricks CLI com token e host
      - name: Configure Databricks CLI
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks configure --token <<EOF
          $DATABRICKS_HOST
          $DATABRICKS_TOKEN
          EOF

      # Passo 5: Rodar testes (ajuste conforme seu projeto)
      # - name: Run tests
      #   run: |
      #     # Exemplo: rodar testes Python com pytest
      #     if [ -f "requirements.txt" ]; then pip install -r requirements.txt; fi
      #     if command -v pytest > /dev/null; then pytest; else echo "pytest não encontrado"; fi

      # Passo 6: Executar comandos do Databricks Assets Bundles
      - name: Run Databricks Assets Bundles commands
        run: 
          databricks-assets-bundles validate # Exemplo: validar assets bundles (ajuste conforme seu uso)
